/*

インタラクティブトランジションデリゲート（このプロトコルをサポートするオブジェクトの呼称）は、タッチイベントや時間的に変化するプログラム入力に応答し、ビューコントローラの遷移の進行を早めたり、遅くしたり、あるいは逆にしたりすることができます。
例えば、ナビゲーションコントローラのインタラクティブな遷移は、ビューコントローラをナビゲーションスタックの上に移動したり、ナビゲーションスタックの外に移動したりすることで、スワイプジェスチャーに応答することができます。

これは UIViewControllerAnimatedTransitioning プロトコルを採用したカスタムオブジェクトです。
トランジションデリゲートとトランジションアニメーターは、単一のカスタムクラスで定義することができます。

代わりに、固定時間のアニメーションによるビューコントローラの遷移（ユーザとの対話をサポートしないもの）を行いたい場合は、遷移アニメータのデリゲートを使用します。
UIViewControllerAnimatedTransitioning を参照ください。

startInteractiveTransition(_:) メソッド内でビュー遷移のコンテキスト情報を取得するためにコールできるメソッドについては UIViewControllerContextTransitioning を参照ください。

*/

import type { UIViewControllerContextTransitioning } from "./UIViewControllerContextTransitioning.js";

export interface UIViewControllerInteractiveTransitioning {
	startInteractiveTransition: (transitionContext: UIViewControllerContextTransitioning) => void;
}