/*

このプロトコルのメソッドでは、アニメータオブジェクトを定義します。
アニメータオブジェクトは、ビューコントローラを一定時間で画面遷移させるためのアニメーションを作成します。
このプロトコルで作成するアニメーションは、インタラクティブなものであってはならない。
インタラクティブな遷移を行うには、 animator オブジェクトと、アニメーションのタイミングを制御する別のオブジェクトを組み合わせる必要があります。

animator オブジェクトでは、 transitionDuration(using:) メソッドを実装して遷移の時間を指定し、 animateTransition(using:) メソッドを実装してアニメーションを作成します。
トランジションに関与するオブジェクトに関する情報は、コンテキスト・オブジェクトの形で animateTransition(using:) メソッドに渡されます。
そのオブジェクトが提供する情報を使用して、指定された期間にわたって、対象のビューコントローラのビューを画面上または画面外に移動させます。

UIViewControllerTransitioningDelegate プロトコルに準拠したオブジェクトです。
ビューコントローラを表示する場合、プレゼンテーションスタイルをUIModalPresentationStyle.customに設定し、transitioningDelegateをビューコントローラのtransitioningDelegateプロパティに割り当てます。
ビューコントローラは、アニメーターオブジェクトを transitioningDelegate から取得し、アニメーションの実行に使用します。
アニメータオブジェクトは、ビューコントローラの表示と終了用に別々に指定することができます。

ビューコントローラの遷移にユーザーとのインタラクションを追加するには、 アニメーターオブジェクトと インタラクティブアニメーターオブジェクト - UIViewControllerInteractiveTransitioning プロトコルを採用したカスタムオブジェクト - を併用する必要があります。
インタラクティブな遷移の定義については UIViewControllerInteractiveTransitioning を参照してください。

*/

export interface UIViewControllerAnimatedTransitioning{
	
}